name: Video Pipeline (R2 Version)
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Install yt-dlp
        run: sudo apt-get update && sudo apt-get install -y yt-dlp
      - name: Download Video
        run: |
          # Finds the keyword in your commit
          KW=$(git log -1 --pretty=%B | grep -oP 'keyword:\s*\K\w+' || echo "")
          if [ -z "$KW" ]; then exit 0; fi
          # Downloads only 720p to save space
          yt-dlp "ytsearch1:$KW" -f "mp4[height<=720]" --get-title --get-id > meta.txt
          TITLE=$(sed -n '1p' meta.txt)
          YT_ID=$(sed -n '2p' meta.txt)
          yt-dlp "https://www.youtube.com/watch?v=$YT_ID" -f "mp4[height<=720]" -o "videos/$YT_ID.mp4"
          # Update the RSS Feed
          PUB_DATE=$(date -R)
          R2_URL="https://YOUR_R2_PUBLIC_URL/videos/$YT_ID.mp4"
          ITEM="<item><title>$TITLE</title><description>YouTube: $YT_ID</description><pubDate>$PUB_DATE</pubDate><enclosure url=\"$R2_URL\" type=\"video/mp4\"/><guid>$YT_ID</guid></item>"
          sed -i "//a $ITEM" feed.xml
      - name: Upload to Cloudflare R2
        uses: ryand56/r2-upload-action@v1.3.1
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2-bucket: "potify-videos"
          source-dir: "videos"
          destination-dir: "videos"
      - name: Save feed.xml back to GitHub
        run: |
          git config user.name "Bot"
          git config user.email "bot@github.com"
          git add feed.xml
          git commit -m "New episode added"
          git push
